# This rule is not used by the project openshift-update-experience itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over openshift.muller.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openshift-update-experience
    app.kubernetes.io/managed-by: kustomize
  name: machineconfigpoolprogressinsight-admin-role
rules:
- apiGroups:
  - openshift.muller.dev
  resources:
  - machineconfigpoolprogressinsights
  verbs:
  - '*'
- apiGroups:
  - openshift.muller.dev
  resources:
  - machineconfigpoolprogressinsights/status
  verbs:
  - get
